### ISSUE TITLE
Hi Is there any way to keep different version of maya using Atools same time?

### ISSUE THREAD

**Issue by CyrusYee** [MKlimenko/aTools_python3#2]
Hi Is there any way to keep different version of maya using Atools same time?
Ty for prvding this solution for maya with python3.
I just wonder how to quarantine different versions of maya with different python2 ad 3.

 Becasue  after installed this “python3 version ”of Atools ,Its functional components pys had still been created in the same
 path：
 C:\Users\xxxx\Documents\maya\scripts  
Wihch means when  works on  python 3version of maya  the others(python 2) cant work . And yes converting back will have the same problem.

**Comment by CyrusYee** [comment]
nvm I just found that  we can using module folder structure to work with it . https://download.autodesk.com/global/docs/maya2014/en_us/index.html?url=files/GUID-130A3F57-2A5D-4E56-B066-6B86F68EEA22.htm,topicNumber=d30e12447

**Comment by MKlimenko** [comment]
I'll take a look at this issue, but not with a high priority, since you have a workaround
