### ISSUE TITLE
little question

### ISSUE THREAD

**Issue by Leonard0388** [MKlimenko/aTools_python3#3]
Hello friend!
i just want ask. is there a way to return motion trail? it's just that the standard tool in maya is very laggy

**Comment by MKlimenko** [comment]
Hi Leonard,

If the original aTools supports returning the motion trail, so should this port.
However, as I understand, this is the function that used to be present only in third-party plugins (like aTools) and made its way into the original Maya. Therefore, I'd suggest using the Maya-provided motion trails as they're much more test-covered.
By the way, motion trails need to take the whole rig into account, so maybe you could speak to your rig department to make it a bit more lightweight.

Feel free to reopen this issue if there's anything you'd like to add.
