### ISSUE TITLE
Blend Issue

### ISSUE THREAD

**Issue by kalemas** [MKlimenko/aTools_python3#4]
Hello! unfortunately blend to frames function is not working with following error message.

Version is latest git of b82f11a88dd96de533bfa795b50fae772a084742

![image](https://github.com/MKlimenko/aTools_python3/assets/638393/63be6e8c-a85e-40ba-b517-567c1647342b)

**Comment by MKlimenko** [comment]
Hi @kalemas! Thanks for reporting this issue. Let me take a look at it and I'll come back to you.
As a recap: you're moving the BF knob and observe this issue, right?

**Comment by MKlimenko** [comment]
Closed due to inactivity, feel free to reopen.
