### ISSUE TITLE
Error Atool maya 2020

### ISSUE THREAD

**Issue by saleemian** [MKlimenko/aTools_python3#5]
Hello
Thank you very much for making this atool for Python 3 and Maya 2023, but there is a problem on my system, I have a more stable version of Maya, like Maya 2020 or a lower version.
And atool doesn't work and gives an error. Is it possible to make it work in all versions of Maya?

**Comment by MKlimenko** [comment]
If you're using older Maya versions, you should use the original aTools, not this python 3 port.

**Comment by saleemian** [comment]
I use both versions of Maya, but one is Python 2 and one is Python 3
Is it not possible for atools to work easily in both versions?

**Comment by MKlimenko** [comment]
Potentially, there is a way to query the Maya version and pull the proper aTools (either original or this modified one), but considering the ease of installation, the fact that it should be done only once and a shrinking market for pre-Python3 Maya I can't say that it's worth the effort.
Please install this port for newer Maya versions and the original one for pre-Python3.
